#ifndef POLYCHROME_H
#define POLYCHROME_H

#define POLYCHROME_NAME "Polychrome"
#define POLYCHROME_API_VERSION "0.1.1"
#define POLYCHROME_API_VERSION_NUM 0x000101
#define POLYCHROME_CALL __stdcall

#ifdef __cplusplus
	#include <cstdint>
#else
	#include <stdint.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct PC_Color8 {
	uint8_t r = 0;
	uint8_t g = 0;
	uint8_t b = 0;
	uint8_t a = 255;
} PC_Color8;

typedef struct PC_Color {
	float r = 0.0;
	float g = 0.0;
	float b = 0.0;
	float a = 1.0;
} PC_Color;

typedef struct PC_ColorHSV {
	float h = 0.0;
	float s = 0.0;
	float v = 0.0;
	float a = 1.0;
} PC_ColorHSV;

#define WHITE   ((PC_Color8){0xFF,0xFF,0xFF,0xFF})
#define RED     ((PC_Color8){0xFF,0x00,0x00,0xFF})
#define GREEN   ((PC_Color8){0x00,0xFF,0x00,0xFF})
#define BLUE    ((PC_Color8){0x00,0x00,0xFF,0xFF})
#define CYAN    ((PC_Color8){0x00,0xFF,0xFF,0xFF})
#define MAGENTA ((PC_Color8){0xFF,0x00,0xFF,0xFF})
#define YELLOW  ((PC_Color8){0xFF,0xFF,0x00,0xFF})
#define BLACK   ((PC_Color8){0x00,0x00,0x00,0xFF})

typedef enum PC_ARGBColorId {
	PC_COLOR_SCREENFLASH_BLACK,
	PC_COLOR_SCREENFLASH_DARK_RED,
	PC_COLOR_SCREENFLASH_DARK_GREEN,
	PC_COLOR_SCREENFLASH_DARK_YELLOW,
	PC_COLOR_SCREENFLASH_DARK_BLUE,
	PC_COLOR_SCREENFLASH_DARK_MAGENTA,
	PC_COLOR_SCREENFLASH_DARK_CYAN,
	PC_COLOR_SCREENFLASH_DARK_GRAY,
	PC_COLOR_SCREENFLASH_GRAY,
	PC_COLOR_SCREENFLASH_RED,
	PC_COLOR_SCREENFLASH_GREEN,
	PC_COLOR_SCREENFLASH_YELLOW,
	PC_COLOR_SCREENFLASH_BLUE,
	PC_COLOR_SCREENFLASH_MAGENTA,
	PC_COLOR_SCREENFLASH_CYAN,
	PC_COLOR_SCREENFLASH_WHITE,
	PC_COLOR_PURPLE_FLASH,
	PC_COLOR_SLASHBACK_FLASH,
	PC_COLOR_WHITE_FLASH,
	PC_COLOR_EASY_FRC_FLASH,
	PC_COLOR_COUNTER_HIT_FLASH,
	PC_COLOR_WHITE_FLASH2,
	PC_COLOR_HEALTHBAR_PR1,
	PC_COLOR_HEALTHBAR_PR2,
	PC_COLOR_ZP_P1_RAOU_GAUGE_BG,
	PC_COLOR_ZP_P2_RAOU_GAUGE_BG,
	PC_COLOR_ZP_RAOU_GAUGE,
	PC_COLOR_DIZZY_BAR1,
	PC_COLOR_DIZZY_BAR2,
	PC_COLOR_HUD0,
	PC_COLOR_RK_GAUGE_LOW,
	PC_COLOR_RK_GAUGE_MID,
	PC_COLOR_RK_GAUGE_HIGH,
	PC_COLOR_ATTACK_GAUGE,
	PC_COLOR_DAMAGE_COMBO,
	PC_COLOR_DAMAGE_HIT_CFADE,
	PC_COLOR_DAMAGE_HIT_FFADE,
	PC_COLOR_RISC_BAR,
	PC_COLOR_RAIN,
	PC_COLOR_ED_GAUGE_EXHAUST,
	PC_COLOR_ED_GAUGE_IDLE,
	PC_COLOR_ED_GAUGE_DECREASE,
	PC_COLOR_ED_GAUGE_RECOVER,
	PC_COLOR_WHITE_FLASH3,
	PC_COLOR_WHITE_FLASH4,
	PC_COLOR_ZP_DOGTINT_P,
	PC_COLOR_ZP_DOGTINT_K,
	PC_COLOR_ZP_DOGTINT_S,
	PC_COLOR_ZP_DOGTINT_H,
	PC_COLOR_ZP_DOGTINT_D,
	PC_COLOR_ZP_DOGTINT_EP,
	PC_COLOR_ZP_DOGTINT_EK,
	PC_COLOR_ZP_DOGTINT_ES,
	PC_COLOR_ZP_DOGTINT_EH,
	PC_COLOR_ZP_DOGTINT_ED,
	PC_COLOR_ZP_DOGTINT_SP,
	PC_COLOR_ZP_DOGTINT_SK,
	PC_COLOR_ZP_DOGTINT_SS,
	PC_COLOR_ZP_DOGTINT_SH,
	PC_COLOR_ZP_DOGTINT_GOLD,
	PC_COLOR_ZP_DOGTINT_RP,
	PC_COLOR_ZP_DOGTINT_RK,
	PC_COLOR_ZP_DOGTINT_RS,
	PC_COLOR_ZP_DOGTINT_RH,
	PC_COLOR_ZP_DOGTINT_SHADOW,
	PC_COLOR_ZP_DOGTINT_SD,
	PC_COLOR_ZP_DOGTINT_RD,
	PC_COLOR_ALTREDFLASH_1,
	PC_COLOR_ALTREDFLASH_2,
	PC_COLOR_ALTREDFLASH_3,
	PC_COLOR_ALTREDFLASH_4,
	PC_COLOR_ALTREDFLASH_5,
	PC_COLOR_ALTREDFLASH_6,
	PC_COLOR_ALTREDFLASH_7,
	PC_COLOR_ALTREDFLASH_8,
	PC_COLOR_RED_FLASH_1,
	PC_COLOR_RED_FLASH_2,
	PC_COLOR_RED_FLASH_3,
	PC_COLOR_RED_FLASH_4,
	PC_COLOR_RED_FLASH_5,
	PC_COLOR_RED_FLASH_6,
	PC_COLOR_RED_FLASH_7,
	PC_COLOR_RED_FLASH_8,
	PC_COLOR_BLUE_FLASH_1,
	PC_COLOR_BLUE_FLASH_2,
	PC_COLOR_BLUE_FLASH_3,
	PC_COLOR_BLUE_FLASH_4,
	PC_COLOR_BLUE_FLASH_5,
	PC_COLOR_BLUE_FLASH_6,
	PC_COLOR_BLUE_FLASH_7,
	PC_COLOR_BLUE_FLASH_8,
	PC_COLOR_MAGENTA_FLASH_1,
	PC_COLOR_MAGENTA_FLASH_2,
	PC_COLOR_MAGENTA_FLASH_3,
	PC_COLOR_MAGENTA_FLASH_4,
	PC_COLOR_MAGENTA_FLASH_5,
	PC_COLOR_MAGENTA_FLASH_6,
	PC_COLOR_MAGENTA_FLASH_7,
	PC_COLOR_MAGENTA_FLASH_8,
	PC_COLOR_GREEN_FLASH_1,
	PC_COLOR_GREEN_FLASH_2,
	PC_COLOR_GREEN_FLASH_3,
	PC_COLOR_GREEN_FLASH_4,
	PC_COLOR_GREEN_FLASH_5,
	PC_COLOR_GREEN_FLASH_6,
	PC_COLOR_GREEN_FLASH_7,
	PC_COLOR_GREEN_FLASH_8,
	PC_COLOR_YELLOW_FLASH_1,
	PC_COLOR_YELLOW_FLASH_2,
	PC_COLOR_YELLOW_FLASH_3,
	PC_COLOR_YELLOW_FLASH_4,
	PC_COLOR_YELLOW_FLASH_5,
	PC_COLOR_YELLOW_FLASH_6,
	PC_COLOR_YELLOW_FLASH_7,
	PC_COLOR_YELLOW_FLASH_8,
	PC_COLOR_CYAN_FLASH_1,
	PC_COLOR_CYAN_FLASH_2,
	PC_COLOR_CYAN_FLASH_3,
	PC_COLOR_CYAN_FLASH_4,
	PC_COLOR_CYAN_FLASH_5,
	PC_COLOR_CYAN_FLASH_6,
	PC_COLOR_CYAN_FLASH_7,
	PC_COLOR_CYAN_FLASH_8,
	PC_COLOR_AFTERIMAGE_1,
	PC_COLOR_AFTERIMAGE_2,
	PC_COLOR_AFTERIMAGE_3,
} PC_ARGBColorId;

typedef struct Polychrome_ColorsetApi {
	uint32_t size;
	uint32_t version;

	PC_Color8 POLYCHROME_CALL (*GetARGBColorById)(int32_t colorId);
	PC_Color8 POLYCHROME_CALL (*GetARGBColorByName)(char* colorName);

	void POLYCHROME_CALL (*SetARGBColorById)(int32_t colorId, PC_Color8 color);
	void POLYCHROME_CALL (*SetARGBColorByName)(char* colorName, PC_Color8 color);
} Polychrome_ColorsetApi;

typedef struct Polychrome_Api {
	uint32_t size;
	uint32_t version;
	
	const Polychrome_ColorsetApi* Colorset;
} Polychrome_Api;

#ifdef __cplusplus
} //extern "C"
#endif

#endif
