#ifndef POLYCHROME_HPP
#define POLYCHROME_HPP

#include "polychrome_c.h"

// Im not knowledgefull of C++, sorry if this is all wrong

namespace Polychrome {

using Color8 = PC_Color8;
using Color = PC_Color;
using ColorHSV = PC_ColorHSV;

enum class ARGBColorId : int32_t {
	SCREENFLASH_BLACK = PC_COLOR_SCREENFLASH_BLACK,
	SCREENFLASH_DARK_RED = PC_COLOR_SCREENFLASH_DARK_RED,
	SCREENFLASH_DARK_GREEN = PC_COLOR_SCREENFLASH_DARK_GREEN,
	SCREENFLASH_DARK_YELLOW = PC_COLOR_SCREENFLASH_DARK_YELLOW,
	SCREENFLASH_DARK_BLUE = PC_COLOR_SCREENFLASH_DARK_BLUE,
	SCREENFLASH_DARK_MAGENTA = PC_COLOR_SCREENFLASH_DARK_MAGENTA,
	SCREENFLASH_DARK_CYAN = PC_COLOR_SCREENFLASH_DARK_CYAN,
	SCREENFLASH_DARK_GRAY = PC_COLOR_SCREENFLASH_DARK_GRAY,
	SCREENFLASH_GRAY = PC_COLOR_SCREENFLASH_GRAY,
	SCREENFLASH_RED = PC_COLOR_SCREENFLASH_RED,
	SCREENFLASH_GREEN = PC_COLOR_SCREENFLASH_GREEN,
	SCREENFLASH_YELLOW = PC_COLOR_SCREENFLASH_YELLOW,
	SCREENFLASH_BLUE = PC_COLOR_SCREENFLASH_BLUE,
	SCREENFLASH_MAGENTA = PC_COLOR_SCREENFLASH_MAGENTA,
	SCREENFLASH_CYAN = PC_COLOR_SCREENFLASH_CYAN,
	SCREENFLASH_WHITE = PC_COLOR_SCREENFLASH_WHITE,
	PURPLE_FLASH = PC_COLOR_PURPLE_FLASH,
	SLASHBACK_FLASH = PC_COLOR_SLASHBACK_FLASH,
	WHITE_FLASH = PC_COLOR_WHITE_FLASH,
	EASY_FRC_FLASH = PC_COLOR_EASY_FRC_FLASH,
	COUNTER_HIT_FLASH = PC_COLOR_COUNTER_HIT_FLASH,
	WHITE_FLASH2 = PC_COLOR_WHITE_FLASH2,
	HEALTHBAR_PR1 = PC_COLOR_HEALTHBAR_PR1,
	HEALTHBAR_PR2 = PC_COLOR_HEALTHBAR_PR2,
	ZP_P1_RAOU_GAUGE_BG = PC_COLOR_ZP_P1_RAOU_GAUGE_BG,
	ZP_P2_RAOU_GAUGE_BG = PC_COLOR_ZP_P2_RAOU_GAUGE_BG,
	ZP_RAOU_GAUGE = PC_COLOR_ZP_RAOU_GAUGE,
	DIZZY_BAR1 = PC_COLOR_DIZZY_BAR1,
	DIZZY_BAR2 = PC_COLOR_DIZZY_BAR2,
	HUD0 = PC_COLOR_HUD0,
	RK_GAUGE_LOW = PC_COLOR_RK_GAUGE_LOW,
	RK_GAUGE_MID = PC_COLOR_RK_GAUGE_MID,
	RK_GAUGE_HIGH = PC_COLOR_RK_GAUGE_HIGH,
	ATTACK_GAUGE = PC_COLOR_ATTACK_GAUGE,
	DAMAGE_COMBO = PC_COLOR_DAMAGE_COMBO,
	DAMAGE_HIT_CFADE = PC_COLOR_DAMAGE_HIT_CFADE,
	DAMAGE_HIT_FFADE = PC_COLOR_DAMAGE_HIT_FFADE,
	RISC_BAR = PC_COLOR_RISC_BAR,
	RAIN = PC_COLOR_RAIN,
	ED_GAUGE_EXHAUST = PC_COLOR_ED_GAUGE_EXHAUST,
	ED_GAUGE_IDLE = PC_COLOR_ED_GAUGE_IDLE,
	ED_GAUGE_DECREASE = PC_COLOR_ED_GAUGE_DECREASE,
	ED_GAUGE_RECOVER = PC_COLOR_ED_GAUGE_RECOVER,
	WHITE_FLASH3 = PC_COLOR_WHITE_FLASH3,
	WHITE_FLASH4 = PC_COLOR_WHITE_FLASH4,
	ZP_DOGTINT_P = PC_COLOR_ZP_DOGTINT_P,
	ZP_DOGTINT_K = PC_COLOR_ZP_DOGTINT_K,
	ZP_DOGTINT_S = PC_COLOR_ZP_DOGTINT_S,
	ZP_DOGTINT_H = PC_COLOR_ZP_DOGTINT_H,
	ZP_DOGTINT_D = PC_COLOR_ZP_DOGTINT_D,
	ZP_DOGTINT_EP = PC_COLOR_ZP_DOGTINT_EP,
	ZP_DOGTINT_EK = PC_COLOR_ZP_DOGTINT_EK,
	ZP_DOGTINT_ES = PC_COLOR_ZP_DOGTINT_ES,
	ZP_DOGTINT_EH = PC_COLOR_ZP_DOGTINT_EH,
	ZP_DOGTINT_ED = PC_COLOR_ZP_DOGTINT_ED,
	ZP_DOGTINT_SP = PC_COLOR_ZP_DOGTINT_SP,
	ZP_DOGTINT_SK = PC_COLOR_ZP_DOGTINT_SK,
	ZP_DOGTINT_SS = PC_COLOR_ZP_DOGTINT_SS,
	ZP_DOGTINT_SH = PC_COLOR_ZP_DOGTINT_SH,
	ZP_DOGTINT_GOLD = PC_COLOR_ZP_DOGTINT_GOLD,
	ZP_DOGTINT_RP = PC_COLOR_ZP_DOGTINT_RP,
	ZP_DOGTINT_RK = PC_COLOR_ZP_DOGTINT_RK,
	ZP_DOGTINT_RS = PC_COLOR_ZP_DOGTINT_RS,
	ZP_DOGTINT_RH = PC_COLOR_ZP_DOGTINT_RH,
	ZP_DOGTINT_SHADOW = PC_COLOR_ZP_DOGTINT_SHADOW,
	ZP_DOGTINT_SD = PC_COLOR_ZP_DOGTINT_SD,
	ZP_DOGTINT_RD = PC_COLOR_ZP_DOGTINT_RD,
	ALTREDFLASH_1 = PC_COLOR_ALTREDFLASH_1,
	ALTREDFLASH_2 = PC_COLOR_ALTREDFLASH_2,
	ALTREDFLASH_3 = PC_COLOR_ALTREDFLASH_3,
	ALTREDFLASH_4 = PC_COLOR_ALTREDFLASH_4,
	ALTREDFLASH_5 = PC_COLOR_ALTREDFLASH_5,
	ALTREDFLASH_6 = PC_COLOR_ALTREDFLASH_6,
	ALTREDFLASH_7 = PC_COLOR_ALTREDFLASH_7,
	ALTREDFLASH_8 = PC_COLOR_ALTREDFLASH_8,
	RED_FLASH_1 = PC_COLOR_RED_FLASH_1,
	RED_FLASH_2 = PC_COLOR_RED_FLASH_2,
	RED_FLASH_3 = PC_COLOR_RED_FLASH_3,
	RED_FLASH_4 = PC_COLOR_RED_FLASH_4,
	RED_FLASH_5 = PC_COLOR_RED_FLASH_5,
	RED_FLASH_6 = PC_COLOR_RED_FLASH_6,
	RED_FLASH_7 = PC_COLOR_RED_FLASH_7,
	RED_FLASH_8 = PC_COLOR_RED_FLASH_8,
	BLUE_FLASH_1 = PC_COLOR_BLUE_FLASH_1,
	BLUE_FLASH_2 = PC_COLOR_BLUE_FLASH_2,
	BLUE_FLASH_3 = PC_COLOR_BLUE_FLASH_3,
	BLUE_FLASH_4 = PC_COLOR_BLUE_FLASH_4,
	BLUE_FLASH_5 = PC_COLOR_BLUE_FLASH_5,
	BLUE_FLASH_6 = PC_COLOR_BLUE_FLASH_6,
	BLUE_FLASH_7 = PC_COLOR_BLUE_FLASH_7,
	BLUE_FLASH_8 = PC_COLOR_BLUE_FLASH_8,
	MAGENTA_FLASH_1 = PC_COLOR_MAGENTA_FLASH_1,
	MAGENTA_FLASH_2 = PC_COLOR_MAGENTA_FLASH_2,
	MAGENTA_FLASH_3 = PC_COLOR_MAGENTA_FLASH_3,
	MAGENTA_FLASH_4 = PC_COLOR_MAGENTA_FLASH_4,
	MAGENTA_FLASH_5 = PC_COLOR_MAGENTA_FLASH_5,
	MAGENTA_FLASH_6 = PC_COLOR_MAGENTA_FLASH_6,
	MAGENTA_FLASH_7 = PC_COLOR_MAGENTA_FLASH_7,
	MAGENTA_FLASH_8 = PC_COLOR_MAGENTA_FLASH_8,
	GREEN_FLASH_1 = PC_COLOR_GREEN_FLASH_1,
	GREEN_FLASH_2 = PC_COLOR_GREEN_FLASH_2,
	GREEN_FLASH_3 = PC_COLOR_GREEN_FLASH_3,
	GREEN_FLASH_4 = PC_COLOR_GREEN_FLASH_4,
	GREEN_FLASH_5 = PC_COLOR_GREEN_FLASH_5,
	GREEN_FLASH_6 = PC_COLOR_GREEN_FLASH_6,
	GREEN_FLASH_7 = PC_COLOR_GREEN_FLASH_7,
	GREEN_FLASH_8 = PC_COLOR_GREEN_FLASH_8,
	YELLOW_FLASH_1 = PC_COLOR_YELLOW_FLASH_1,
	YELLOW_FLASH_2 = PC_COLOR_YELLOW_FLASH_2,
	YELLOW_FLASH_3 = PC_COLOR_YELLOW_FLASH_3,
	YELLOW_FLASH_4 = PC_COLOR_YELLOW_FLASH_4,
	YELLOW_FLASH_5 = PC_COLOR_YELLOW_FLASH_5,
	YELLOW_FLASH_6 = PC_COLOR_YELLOW_FLASH_6,
	YELLOW_FLASH_7 = PC_COLOR_YELLOW_FLASH_7,
	YELLOW_FLASH_8 = PC_COLOR_YELLOW_FLASH_8,
	CYAN_FLASH_1 = PC_COLOR_CYAN_FLASH_1,
	CYAN_FLASH_2 = PC_COLOR_CYAN_FLASH_2,
	CYAN_FLASH_3 = PC_COLOR_CYAN_FLASH_3,
	CYAN_FLASH_4 = PC_COLOR_CYAN_FLASH_4,
	CYAN_FLASH_5 = PC_COLOR_CYAN_FLASH_5,
	CYAN_FLASH_6 = PC_COLOR_CYAN_FLASH_6,
	CYAN_FLASH_7 = PC_COLOR_CYAN_FLASH_7,
	CYAN_FLASH_8 = PC_COLOR_CYAN_FLASH_8,
	AFTERIMAGE_1 = PC_COLOR_AFTERIMAGE_1,
	AFTERIMAGE_2 = PC_COLOR_AFTERIMAGE_2,
	AFTERIMAGE_3 = PC_COLOR_AFTERIMAGE_3,
};

template<typename T>
class ApiWrapper {
public:
	ApiWrapper() : _ref(nullptr) {}
	ApiWrapper(const T* ref) : _ref(ref) {}
	bool VersionError() {
		return (POLYCHROME_API_VERSION_NUM & 0xFF0000) != (reinterpret_cast<CApiBase*>(_ref)->version & 0xFF0000);
	}
	bool IsValid() { return _ref != nullptr; }
	const T* GetCApi() { return _ref; }
protected:
	const T* _ref;
private:
	struct CApiBase {
		uint32_t size;
		uint32_t version;
	};
};

class ColorsetApi : public ApiWrapper<Polychrome_ColorsetApi> {
public:
	Color8 GetARGBColorById(ARGBColorId colorId) {
		_ref->GetARGBColorById(static_cast<int32_t>(colorId));
	}
	Color8 GetARGBColorByName(std::string colorName) {
		_ref->GetARGBColorByName(colorName.c_str());
	}

	void SetARGBColorById(ARGBColorId colorId, Color8 color) {
		_ref->SetARGBColorById(static_cast<int32_t>(colorId),color);
	}
	void SetARGBColorByName(std::string colorName, Color8 color) {
		_ref->SetARGBColorByName(colorName.c_str(),color);
	}
};

class Api : public ApiWrapper<Polychrome_Api> {
public:
	Api()
		: ApiWrapper()
		, Colorset() { }
	Api(const Polychrome_Api* ref)
		: ApiWrapper(ref)
		, Colorset(ref->Colorset) { }

	ColorsetApi Colorset;
};

}

#endif
